#cloud-config
passwd:
  users:
   - name: "takei"
     ssh-authorized-keys:
       - ""
     create:
       home_dir: "/home/takei"
       no_create_home: false
       groups: "wheel"
       shell: "/bin/zsh"
networkd:
  units:
    - name: static.network
      contents: |
        [Match]
        Name=enp2s0

        [Network]
        DNS=192.168.0.2
        Address=192.168.0.15/24
        Gateway=192.168.0.1
